import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        surface: "var(--surface)",
        "surface-low": "var(--surface-container-low)",
        "surface-container": "var(--surface-container)",
        "surface-high": "var(--surface-container-high)",
        primary: "var(--primary)",
        "primary-hover": "var(--primary-hover)",
        "primary-foreground": "var(--primary-foreground)",
        accent: "var(--accent)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        card: "var(--surface)",
        "card-border": "var(--card-border)",
        sidebar: "var(--sidebar)",
        "sidebar-foreground": "var(--sidebar-foreground)",
        "sidebar-muted": "var(--sidebar-muted)",
        "sidebar-border": "var(--sidebar-border)",
        border: "var(--card-border)",
        input: "var(--card-border)",
        secondary: "var(--surface-container)",
        "secondary-foreground": "var(--foreground)",
        "secondary-hover": "var(--surface-container-high)",
        success: "var(--success)",
        "success-bg": "var(--success-bg)",
        "success-border": "var(--success-border)",
        warning: "var(--warning)",
        "warning-bg": "var(--warning-bg)",
        "warning-border": "var(--warning-border)",
        danger: "var(--danger)",
        "danger-bg": "var(--danger-bg)",
        "danger-border": "var(--danger-border)",
        "mistral-orange": "var(--mistral-orange)",
        "mistral-flame": "var(--mistral-flame)",
        "sunshine-900": "var(--sunshine-900)",
        "sunshine-700": "var(--sunshine-700)",
        "sunshine-500": "var(--sunshine-500)",
        "sunshine-300": "var(--sunshine-300)",
        "block-gold": "var(--block-gold)",
        "bright-yellow": "var(--bright-yellow)",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "sans-serif"],
        display: ["var(--font-display)", "sans-serif"],
      },
      boxShadow: {
        apple: "var(--shadow-golden-sm)",
        "apple-hover": "var(--shadow-golden)",
        golden: "var(--shadow-golden)",
        "golden-sm": "var(--shadow-golden-sm)",
        ink: "var(--shadow-ink)",
      },
      borderRadius: {
        apple: "0.875rem",
        "apple-lg": "1rem",
        "apple-xl": "1.25rem",
        "apple-sm": "0.5rem",
        sharp: "0.5rem",
      }
    },
  },
  plugins: [],
};
export default config;
