import { spawnSync } from 'child_process';
import fs from 'fs';
import os from 'os';
import path from 'path';

export const isWindows = os.platform() === 'win32';
export const npmCmd = isWindows ? 'npm.cmd' : 'npm';
export const npxCmd = isWindows ? 'npx.cmd' : 'npx';
export const appDirName = '.jobhunt-india';

export function loadDotEnv(envPath = path.resolve(process.cwd(), '.env.local')) {
  if (!fs.existsSync(envPath)) return;

  const raw = fs.readFileSync(envPath, 'utf8');
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const equalsIndex = trimmed.indexOf('=');
    if (equalsIndex === -1) continue;

    const key = trimmed.slice(0, equalsIndex).trim();
    let value = trimmed.slice(equalsIndex + 1).trim();
    if (!key || process.env[key]) continue;

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    process.env[key] = value;
  }
}

export function getBaseDir() {
  return process.env.JOBHUNT_DATA_DIR
    ? path.resolve(process.env.JOBHUNT_DATA_DIR)
    : path.join(os.homedir(), appDirName);
}

export function ensureDataDirectories(baseDir = getBaseDir()) {
  const dirs = [
    // Core
    baseDir,
    path.join(baseDir, 'config'),
    path.join(baseDir, 'db'),
    path.join(baseDir, 'backups'),
    path.join(baseDir, 'logs'),
    // Uploads (resume PDFs, DOCX uploaded by user)
    path.join(baseDir, 'uploads'),
    path.join(baseDir, 'uploads', 'resumes'),
    // Generated / output documents
    path.join(baseDir, 'output'),
    path.join(baseDir, 'output', 'resumes'),
    path.join(baseDir, 'output', 'cover-letters'),
    path.join(baseDir, 'output', 'outreach'),
    path.join(baseDir, 'output', 'exports'),
    // ML / search
    path.join(baseDir, 'embeddings'),
    path.join(baseDir, 'cache'),
    // AI coach conversation history
    path.join(baseDir, 'coach'),
    // Legacy exports root (kept for back-compat)
    path.join(baseDir, 'exports'),
  ];

  for (const dir of dirs) {
    fs.mkdirSync(dir, { recursive: true });
  }
  return dirs;
}

/**
 * Ensure .env.local exists in the project root with required default values.
 *
 * Rules:
 *  - Never overwrites the file if it already exists — user customisations are preserved.
 *  - If the file exists but is missing a key, that key is appended.
 *  - REDIS_URL must always be present so the BullMQ worker starts even on fresh installs
 *    that have no explicit Redis configuration.
 */
export function ensureEnvFile(projectRoot = process.cwd()) {
  const envPath = path.join(projectRoot, '.env.local');

  /** Key → default value for keys that MUST exist */
  const required = {
    REDIS_URL: 'redis://127.0.0.1:6379',
  };

  // Parse existing file (if present)
  let existing = {};
  if (fs.existsSync(envPath)) {
    for (const line of fs.readFileSync(envPath, 'utf8').split(/\r?\n/)) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eq = trimmed.indexOf('=');
      if (eq === -1) continue;
      existing[trimmed.slice(0, eq).trim()] = true;
    }
  }

  // Collect missing keys
  const missing = Object.entries(required).filter(([key]) => !existing[key]);
  if (missing.length === 0) return envPath; // nothing to do

  // Append missing keys (with a header comment on first write)
  const isNew = !fs.existsSync(envPath);
  const lines = [];
  if (isNew) {
    lines.push('# Career Seek local configuration — generated by bootstrap');
    lines.push('# Edit this file to override defaults. It is .gitignored and never committed.');
    lines.push('');
  } else {
    lines.push('');
    lines.push('# Added by Career Seek bootstrap');
  }
  for (const [key, value] of missing) {
    lines.push(`${key}=${value}`);
  }
  lines.push('');

  fs.appendFileSync(envPath, lines.join('\n'));

  if (isNew) {
    console.log(`Created .env.local at ${envPath}`);
  } else {
    console.log(`Updated .env.local — added: ${missing.map(([k]) => k).join(', ')}`);
  }
  return envPath;
}

export function ensureSettingsFile(baseDir = getBaseDir()) {
  const settingsPath = path.join(baseDir, 'config', 'settings.json');
  if (!fs.existsSync(settingsPath)) {
    fs.writeFileSync(settingsPath, JSON.stringify({
      isConfigured: false,
      onboardingStage: 'welcome',
      onboardingVersion: 2,
    }, null, 2));
  }
  return settingsPath;
}

export function run(bin, args = [], options = {}) {
  const result = spawnSync(bin, args, {
    stdio: 'inherit',
    env: { ...process.env, ...(options.env || {}) },
    cwd: options.cwd || process.cwd(),
    shell: false,
  });

  if (result.error) {
    throw result.error;
  }
  if (result.status !== 0) {
    const printable = [bin, ...args].join(' ');
    throw new Error(`Command failed (${result.status ?? 'unknown'}): ${printable}`);
  }
  return result;
}

export function commandExists(command) {
  const result = isWindows
    ? spawnSync('where.exe', [command], { stdio: 'ignore' })
    : spawnSync('sh', ['-lc', `command -v ${JSON.stringify(command)} >/dev/null 2>&1`], { stdio: 'ignore' });
  return result.status === 0;
}

export function readPackageJson() {
  return JSON.parse(fs.readFileSync(path.resolve(process.cwd(), 'package.json'), 'utf8'));
}

export function nodeMajor() {
  return Number.parseInt(process.versions.node.split('.')[0] || '0', 10);
}
